<?xml version="1.0" encoding="utf-8"?><Database Name="CSTable" Class="DataAccsessDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\CSTable.mdf;Integrated Security=True" SettingsObjectName="DATAACCESS.Properties.Settings" SettingsPropertyName="CSTableConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.C" Member="Cs">
    <Type Name="C">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="peso" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="A" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ix" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Iy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ry" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ProfCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fabrication" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CS" Member="C1s">
    <Type Name="C1">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="peso" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="A" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ix" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Iy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ry" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ProfCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fabrication" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="R" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.W" Member="Ws">
    <Type Name="W">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="peso" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="A" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ix" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Iy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ry" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ProfCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fabrication" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="R" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CX" Member="CXes">
    <Type Name="CX">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="peso" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="A" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ix" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Iy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ry" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ProfCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fabrication" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PS" Member="Ps">
    <Type Name="P">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="peso" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="A" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ix" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Iy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ry" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ProfCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fabrication" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="R" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PSa" Member="PSas">
    <Type Name="PSa">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="peso" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="A" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bfs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bfi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tfs" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="tfi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ix" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wxs" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wxi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Iy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ry" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ProfCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fabrication" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="R" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.sqlite_sequence" Member="sqlite_sequences">
    <Type Name="sqlite_sequence">
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="seq" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.T" Member="Ts">
    <Type Name="T">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="peso" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="A" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ix" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Iy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ry" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ProfCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fabrication" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TQ" Member="TQs">
    <Type Name="TQ">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="peso" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="A" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ix" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Iy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ry" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ProfCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fabrication" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TR" Member="TRs">
    <Type Name="TR">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="peso" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="A" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ix" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Iy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ry" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ProfCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fabrication" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TW" Member="TWs">
    <Type Name="TW">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="peso" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="A" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tw" Member="tw1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ix" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Iy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ry" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ProfCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fabrication" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VS" Member="Vs">
    <Type Name="V">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="peso" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="A" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ix" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Iy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ry" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ProfCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fabrication" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="R" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VSM" Member="VSMs">
    <Type Name="VSM">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="peso" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="A" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bfs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bfi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tfs" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="tfi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ix" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wxs" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wxi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Iy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ry" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ProfCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fabrication" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="R" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Material" Member="Materials">
    <Type Name="Material">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="E" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="G" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Fy" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Fu" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="unitWeight" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CVS" Member="CVs">
    <Type Name="CV">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nome" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="peso" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="A" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="d" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tf" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Ix" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zx" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Iy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Wy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ry" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Zy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="rT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cw" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ProfCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fabrication" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="R" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>