#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATAACCESS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CSTable")]
	public partial class DataAccsessDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMaterial(Material instance);
    partial void UpdateMaterial(Material instance);
    partial void DeleteMaterial(Material instance);
    #endregion
		
		public DataAccsessDataClassesDataContext() : 
				base(global::DATAACCESS.Properties.Settings.Default.CSTableConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataAccsessDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAccsessDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAccsessDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataAccsessDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<C> C
		{
			get
			{
				return this.GetTable<C>();
			}
		}
		
		public System.Data.Linq.Table<CS> CS
		{
			get
			{
				return this.GetTable<CS>();
			}
		}
		
		public System.Data.Linq.Table<W> W
		{
			get
			{
				return this.GetTable<W>();
			}
		}
		
		public System.Data.Linq.Table<CX> CX
		{
			get
			{
				return this.GetTable<CX>();
			}
		}
		
		public System.Data.Linq.Table<PS> PS
		{
			get
			{
				return this.GetTable<PS>();
			}
		}
		
		public System.Data.Linq.Table<PSa> PSa
		{
			get
			{
				return this.GetTable<PSa>();
			}
		}
		
		public System.Data.Linq.Table<sqlite_sequence> sqlite_sequences
		{
			get
			{
				return this.GetTable<sqlite_sequence>();
			}
		}
		
		public System.Data.Linq.Table<T> T
		{
			get
			{
				return this.GetTable<T>();
			}
		}
		
		public System.Data.Linq.Table<TQ> TQ
		{
			get
			{
				return this.GetTable<TQ>();
			}
		}
		
		public System.Data.Linq.Table<TR> TR
		{
			get
			{
				return this.GetTable<TR>();
			}
		}
		
		public System.Data.Linq.Table<TW> TW
		{
			get
			{
				return this.GetTable<TW>();
			}
		}
		
		public System.Data.Linq.Table<VS> VS
		{
			get
			{
				return this.GetTable<VS>();
			}
		}
		
		public System.Data.Linq.Table<VSM> VSM
		{
			get
			{
				return this.GetTable<VSM>();
			}
		}
		
		public System.Data.Linq.Table<Material> Materials
		{
			get
			{
				return this.GetTable<Material>();
			}
		}
		
		public System.Data.Linq.Table<CVS> CVS
		{
			get
			{
				return this.GetTable<CVS>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.C")]
	public partial class C
	{
		
		private System.Nullable<int> _ID;
		
		private string _nome;
		
		private System.Nullable<double> _peso;
		
		private System.Nullable<double> _A;
		
		private System.Nullable<int> _d;
		
		private System.Nullable<double> _tw;
		
		private System.Nullable<int> _bf;
		
		private System.Nullable<double> _tf;
		
		private System.Nullable<double> _Ix;
		
		private System.Nullable<double> _Wx;
		
		private System.Nullable<double> _rx;
		
		private System.Nullable<double> _Zx;
		
		private System.Nullable<double> _Iy;
		
		private System.Nullable<double> _Wy;
		
		private System.Nullable<double> _ry;
		
		private System.Nullable<double> _Zy;
		
		private System.Nullable<double> _rT;
		
		private System.Nullable<double> _IT;
		
		private System.Nullable<double> _Cw;
		
		private System.Nullable<int> _ProfCode;
		
		private System.Nullable<int> _Fabrication;
		
		public C()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(50)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this._nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Float")]
		public System.Nullable<double> peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this._peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Float")]
		public System.Nullable<double> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this._A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d", DbType="Int")]
		public System.Nullable<int> d
		{
			get
			{
				return this._d;
			}
			set
			{
				if ((this._d != value))
				{
					this._d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tw", DbType="Float")]
		public System.Nullable<double> tw
		{
			get
			{
				return this._tw;
			}
			set
			{
				if ((this._tw != value))
				{
					this._tw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bf", DbType="Int")]
		public System.Nullable<int> bf
		{
			get
			{
				return this._bf;
			}
			set
			{
				if ((this._bf != value))
				{
					this._bf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tf", DbType="Float")]
		public System.Nullable<double> tf
		{
			get
			{
				return this._tf;
			}
			set
			{
				if ((this._tf != value))
				{
					this._tf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ix", DbType="Float")]
		public System.Nullable<double> Ix
		{
			get
			{
				return this._Ix;
			}
			set
			{
				if ((this._Ix != value))
				{
					this._Ix = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wx", DbType="Float")]
		public System.Nullable<double> Wx
		{
			get
			{
				return this._Wx;
			}
			set
			{
				if ((this._Wx != value))
				{
					this._Wx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rx", DbType="Float")]
		public System.Nullable<double> rx
		{
			get
			{
				return this._rx;
			}
			set
			{
				if ((this._rx != value))
				{
					this._rx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zx", DbType="Float")]
		public System.Nullable<double> Zx
		{
			get
			{
				return this._Zx;
			}
			set
			{
				if ((this._Zx != value))
				{
					this._Zx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iy", DbType="Float")]
		public System.Nullable<double> Iy
		{
			get
			{
				return this._Iy;
			}
			set
			{
				if ((this._Iy != value))
				{
					this._Iy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wy", DbType="Float")]
		public System.Nullable<double> Wy
		{
			get
			{
				return this._Wy;
			}
			set
			{
				if ((this._Wy != value))
				{
					this._Wy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ry", DbType="Float")]
		public System.Nullable<double> ry
		{
			get
			{
				return this._ry;
			}
			set
			{
				if ((this._ry != value))
				{
					this._ry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zy", DbType="Float")]
		public System.Nullable<double> Zy
		{
			get
			{
				return this._Zy;
			}
			set
			{
				if ((this._Zy != value))
				{
					this._Zy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rT", DbType="Float")]
		public System.Nullable<double> rT
		{
			get
			{
				return this._rT;
			}
			set
			{
				if ((this._rT != value))
				{
					this._rT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IT", DbType="Float")]
		public System.Nullable<double> IT
		{
			get
			{
				return this._IT;
			}
			set
			{
				if ((this._IT != value))
				{
					this._IT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cw", DbType="Float")]
		public System.Nullable<double> Cw
		{
			get
			{
				return this._Cw;
			}
			set
			{
				if ((this._Cw != value))
				{
					this._Cw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfCode", DbType="Int")]
		public System.Nullable<int> ProfCode
		{
			get
			{
				return this._ProfCode;
			}
			set
			{
				if ((this._ProfCode != value))
				{
					this._ProfCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fabrication", DbType="Int")]
		public System.Nullable<int> Fabrication
		{
			get
			{
				return this._Fabrication;
			}
			set
			{
				if ((this._Fabrication != value))
				{
					this._Fabrication = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CS")]
	public partial class CS
	{
		
		private System.Nullable<int> _ID;
		
		private string _nome;
		
		private System.Nullable<double> _peso;
		
		private System.Nullable<double> _A;
		
		private System.Nullable<int> _d;
		
		private System.Nullable<double> _tw;
		
		private System.Nullable<int> _bf;
		
		private System.Nullable<double> _tf;
		
		private System.Nullable<double> _Ix;
		
		private System.Nullable<double> _Wx;
		
		private System.Nullable<double> _rx;
		
		private System.Nullable<double> _Zx;
		
		private System.Nullable<double> _Iy;
		
		private System.Nullable<double> _Wy;
		
		private System.Nullable<double> _ry;
		
		private System.Nullable<double> _Zy;
		
		private System.Nullable<double> _rT;
		
		private System.Nullable<double> _IT;
		
		private System.Nullable<double> _Cw;
		
		private System.Nullable<int> _ProfCode;
		
		private System.Nullable<int> _Fabrication;
		
		private System.Nullable<int> _R;
		
		public CS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(50)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this._nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Float")]
		public System.Nullable<double> peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this._peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Float")]
		public System.Nullable<double> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this._A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d", DbType="Int")]
		public System.Nullable<int> d
		{
			get
			{
				return this._d;
			}
			set
			{
				if ((this._d != value))
				{
					this._d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tw", DbType="Float")]
		public System.Nullable<double> tw
		{
			get
			{
				return this._tw;
			}
			set
			{
				if ((this._tw != value))
				{
					this._tw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bf", DbType="Int")]
		public System.Nullable<int> bf
		{
			get
			{
				return this._bf;
			}
			set
			{
				if ((this._bf != value))
				{
					this._bf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tf", DbType="Float")]
		public System.Nullable<double> tf
		{
			get
			{
				return this._tf;
			}
			set
			{
				if ((this._tf != value))
				{
					this._tf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ix", DbType="Float")]
		public System.Nullable<double> Ix
		{
			get
			{
				return this._Ix;
			}
			set
			{
				if ((this._Ix != value))
				{
					this._Ix = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wx", DbType="Float")]
		public System.Nullable<double> Wx
		{
			get
			{
				return this._Wx;
			}
			set
			{
				if ((this._Wx != value))
				{
					this._Wx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rx", DbType="Float")]
		public System.Nullable<double> rx
		{
			get
			{
				return this._rx;
			}
			set
			{
				if ((this._rx != value))
				{
					this._rx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zx", DbType="Float")]
		public System.Nullable<double> Zx
		{
			get
			{
				return this._Zx;
			}
			set
			{
				if ((this._Zx != value))
				{
					this._Zx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iy", DbType="Float")]
		public System.Nullable<double> Iy
		{
			get
			{
				return this._Iy;
			}
			set
			{
				if ((this._Iy != value))
				{
					this._Iy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wy", DbType="Float")]
		public System.Nullable<double> Wy
		{
			get
			{
				return this._Wy;
			}
			set
			{
				if ((this._Wy != value))
				{
					this._Wy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ry", DbType="Float")]
		public System.Nullable<double> ry
		{
			get
			{
				return this._ry;
			}
			set
			{
				if ((this._ry != value))
				{
					this._ry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zy", DbType="Float")]
		public System.Nullable<double> Zy
		{
			get
			{
				return this._Zy;
			}
			set
			{
				if ((this._Zy != value))
				{
					this._Zy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rT", DbType="Float")]
		public System.Nullable<double> rT
		{
			get
			{
				return this._rT;
			}
			set
			{
				if ((this._rT != value))
				{
					this._rT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IT", DbType="Float")]
		public System.Nullable<double> IT
		{
			get
			{
				return this._IT;
			}
			set
			{
				if ((this._IT != value))
				{
					this._IT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cw", DbType="Float")]
		public System.Nullable<double> Cw
		{
			get
			{
				return this._Cw;
			}
			set
			{
				if ((this._Cw != value))
				{
					this._Cw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfCode", DbType="Int")]
		public System.Nullable<int> ProfCode
		{
			get
			{
				return this._ProfCode;
			}
			set
			{
				if ((this._ProfCode != value))
				{
					this._ProfCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fabrication", DbType="Int")]
		public System.Nullable<int> Fabrication
		{
			get
			{
				return this._Fabrication;
			}
			set
			{
				if ((this._Fabrication != value))
				{
					this._Fabrication = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="Int")]
		public System.Nullable<int> R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this._R = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.W")]
	public partial class W
	{
		
		private System.Nullable<int> _ID;
		
		private string _nome;
		
		private System.Nullable<double> _peso;
		
		private System.Nullable<double> _A;
		
		private System.Nullable<int> _d;
		
		private System.Nullable<double> _tw;
		
		private System.Nullable<int> _bf;
		
		private System.Nullable<double> _tf;
		
		private System.Nullable<double> _Ix;
		
		private System.Nullable<double> _Wx;
		
		private System.Nullable<double> _rx;
		
		private System.Nullable<double> _Zx;
		
		private System.Nullable<double> _Iy;
		
		private System.Nullable<double> _Wy;
		
		private System.Nullable<double> _ry;
		
		private System.Nullable<double> _Zy;
		
		private System.Nullable<double> _rT;
		
		private System.Nullable<double> _IT;
		
		private System.Nullable<double> _Cw;
		
		private System.Nullable<int> _ProfCode;
		
		private System.Nullable<int> _Fabrication;
		
		private System.Nullable<int> _R;
		
		public W()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(50)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this._nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Float")]
		public System.Nullable<double> peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this._peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Float")]
		public System.Nullable<double> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this._A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d", DbType="Int")]
		public System.Nullable<int> d
		{
			get
			{
				return this._d;
			}
			set
			{
				if ((this._d != value))
				{
					this._d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tw", DbType="Float")]
		public System.Nullable<double> tw
		{
			get
			{
				return this._tw;
			}
			set
			{
				if ((this._tw != value))
				{
					this._tw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bf", DbType="Int")]
		public System.Nullable<int> bf
		{
			get
			{
				return this._bf;
			}
			set
			{
				if ((this._bf != value))
				{
					this._bf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tf", DbType="Float")]
		public System.Nullable<double> tf
		{
			get
			{
				return this._tf;
			}
			set
			{
				if ((this._tf != value))
				{
					this._tf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ix", DbType="Float")]
		public System.Nullable<double> Ix
		{
			get
			{
				return this._Ix;
			}
			set
			{
				if ((this._Ix != value))
				{
					this._Ix = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wx", DbType="Float")]
		public System.Nullable<double> Wx
		{
			get
			{
				return this._Wx;
			}
			set
			{
				if ((this._Wx != value))
				{
					this._Wx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rx", DbType="Float")]
		public System.Nullable<double> rx
		{
			get
			{
				return this._rx;
			}
			set
			{
				if ((this._rx != value))
				{
					this._rx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zx", DbType="Float")]
		public System.Nullable<double> Zx
		{
			get
			{
				return this._Zx;
			}
			set
			{
				if ((this._Zx != value))
				{
					this._Zx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iy", DbType="Float")]
		public System.Nullable<double> Iy
		{
			get
			{
				return this._Iy;
			}
			set
			{
				if ((this._Iy != value))
				{
					this._Iy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wy", DbType="Float")]
		public System.Nullable<double> Wy
		{
			get
			{
				return this._Wy;
			}
			set
			{
				if ((this._Wy != value))
				{
					this._Wy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ry", DbType="Float")]
		public System.Nullable<double> ry
		{
			get
			{
				return this._ry;
			}
			set
			{
				if ((this._ry != value))
				{
					this._ry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zy", DbType="Float")]
		public System.Nullable<double> Zy
		{
			get
			{
				return this._Zy;
			}
			set
			{
				if ((this._Zy != value))
				{
					this._Zy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rT", DbType="Float")]
		public System.Nullable<double> rT
		{
			get
			{
				return this._rT;
			}
			set
			{
				if ((this._rT != value))
				{
					this._rT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IT", DbType="Float")]
		public System.Nullable<double> IT
		{
			get
			{
				return this._IT;
			}
			set
			{
				if ((this._IT != value))
				{
					this._IT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cw", DbType="Float")]
		public System.Nullable<double> Cw
		{
			get
			{
				return this._Cw;
			}
			set
			{
				if ((this._Cw != value))
				{
					this._Cw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfCode", DbType="Int")]
		public System.Nullable<int> ProfCode
		{
			get
			{
				return this._ProfCode;
			}
			set
			{
				if ((this._ProfCode != value))
				{
					this._ProfCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fabrication", DbType="Int")]
		public System.Nullable<int> Fabrication
		{
			get
			{
				return this._Fabrication;
			}
			set
			{
				if ((this._Fabrication != value))
				{
					this._Fabrication = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="Int")]
		public System.Nullable<int> R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this._R = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CX")]
	public partial class CX
	{
		
		private System.Nullable<int> _ID;
		
		private string _nome;
		
		private System.Nullable<double> _peso;
		
		private System.Nullable<double> _A;
		
		private System.Nullable<int> _d;
		
		private System.Nullable<double> _tw;
		
		private System.Nullable<int> _bf;
		
		private System.Nullable<double> _tf;
		
		private System.Nullable<double> _Ix;
		
		private System.Nullable<double> _Wx;
		
		private System.Nullable<double> _rx;
		
		private System.Nullable<double> _Zx;
		
		private System.Nullable<double> _Iy;
		
		private System.Nullable<double> _Wy;
		
		private System.Nullable<double> _ry;
		
		private System.Nullable<double> _Zy;
		
		private System.Nullable<double> _rT;
		
		private System.Nullable<double> _IT;
		
		private System.Nullable<double> _Cw;
		
		private System.Nullable<int> _ProfCode;
		
		private System.Nullable<int> _Fabrication;
		
		public CX()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(50)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this._nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Float")]
		public System.Nullable<double> peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this._peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Float")]
		public System.Nullable<double> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this._A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d", DbType="Int")]
		public System.Nullable<int> d
		{
			get
			{
				return this._d;
			}
			set
			{
				if ((this._d != value))
				{
					this._d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tw", DbType="Float")]
		public System.Nullable<double> tw
		{
			get
			{
				return this._tw;
			}
			set
			{
				if ((this._tw != value))
				{
					this._tw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bf", DbType="Int")]
		public System.Nullable<int> bf
		{
			get
			{
				return this._bf;
			}
			set
			{
				if ((this._bf != value))
				{
					this._bf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tf", DbType="Float")]
		public System.Nullable<double> tf
		{
			get
			{
				return this._tf;
			}
			set
			{
				if ((this._tf != value))
				{
					this._tf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ix", DbType="Float")]
		public System.Nullable<double> Ix
		{
			get
			{
				return this._Ix;
			}
			set
			{
				if ((this._Ix != value))
				{
					this._Ix = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wx", DbType="Float")]
		public System.Nullable<double> Wx
		{
			get
			{
				return this._Wx;
			}
			set
			{
				if ((this._Wx != value))
				{
					this._Wx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rx", DbType="Float")]
		public System.Nullable<double> rx
		{
			get
			{
				return this._rx;
			}
			set
			{
				if ((this._rx != value))
				{
					this._rx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zx", DbType="Float")]
		public System.Nullable<double> Zx
		{
			get
			{
				return this._Zx;
			}
			set
			{
				if ((this._Zx != value))
				{
					this._Zx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iy", DbType="Float")]
		public System.Nullable<double> Iy
		{
			get
			{
				return this._Iy;
			}
			set
			{
				if ((this._Iy != value))
				{
					this._Iy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wy", DbType="Float")]
		public System.Nullable<double> Wy
		{
			get
			{
				return this._Wy;
			}
			set
			{
				if ((this._Wy != value))
				{
					this._Wy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ry", DbType="Float")]
		public System.Nullable<double> ry
		{
			get
			{
				return this._ry;
			}
			set
			{
				if ((this._ry != value))
				{
					this._ry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zy", DbType="Float")]
		public System.Nullable<double> Zy
		{
			get
			{
				return this._Zy;
			}
			set
			{
				if ((this._Zy != value))
				{
					this._Zy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rT", DbType="Float")]
		public System.Nullable<double> rT
		{
			get
			{
				return this._rT;
			}
			set
			{
				if ((this._rT != value))
				{
					this._rT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IT", DbType="Float")]
		public System.Nullable<double> IT
		{
			get
			{
				return this._IT;
			}
			set
			{
				if ((this._IT != value))
				{
					this._IT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cw", DbType="Float")]
		public System.Nullable<double> Cw
		{
			get
			{
				return this._Cw;
			}
			set
			{
				if ((this._Cw != value))
				{
					this._Cw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfCode", DbType="Int")]
		public System.Nullable<int> ProfCode
		{
			get
			{
				return this._ProfCode;
			}
			set
			{
				if ((this._ProfCode != value))
				{
					this._ProfCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fabrication", DbType="Int")]
		public System.Nullable<int> Fabrication
		{
			get
			{
				return this._Fabrication;
			}
			set
			{
				if ((this._Fabrication != value))
				{
					this._Fabrication = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PS")]
	public partial class PS
	{
		
		private System.Nullable<int> _ID;
		
		private string _nome;
		
		private System.Nullable<double> _peso;
		
		private System.Nullable<double> _A;
		
		private System.Nullable<int> _d;
		
		private System.Nullable<double> _tw;
		
		private System.Nullable<int> _bf;
		
		private System.Nullable<double> _tf;
		
		private System.Nullable<double> _Ix;
		
		private System.Nullable<double> _Wx;
		
		private System.Nullable<double> _rx;
		
		private System.Nullable<double> _Zx;
		
		private System.Nullable<double> _Iy;
		
		private System.Nullable<double> _Wy;
		
		private System.Nullable<double> _ry;
		
		private System.Nullable<double> _Zy;
		
		private System.Nullable<double> _rT;
		
		private System.Nullable<double> _IT;
		
		private System.Nullable<double> _Cw;
		
		private System.Nullable<int> _ProfCode;
		
		private System.Nullable<int> _Fabrication;
		
		private System.Nullable<int> _R;
		
		public PS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(50)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this._nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Float")]
		public System.Nullable<double> peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this._peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Float")]
		public System.Nullable<double> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this._A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d", DbType="Int")]
		public System.Nullable<int> d
		{
			get
			{
				return this._d;
			}
			set
			{
				if ((this._d != value))
				{
					this._d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tw", DbType="Float")]
		public System.Nullable<double> tw
		{
			get
			{
				return this._tw;
			}
			set
			{
				if ((this._tw != value))
				{
					this._tw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bf", DbType="Int")]
		public System.Nullable<int> bf
		{
			get
			{
				return this._bf;
			}
			set
			{
				if ((this._bf != value))
				{
					this._bf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tf", DbType="Float")]
		public System.Nullable<double> tf
		{
			get
			{
				return this._tf;
			}
			set
			{
				if ((this._tf != value))
				{
					this._tf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ix", DbType="Float")]
		public System.Nullable<double> Ix
		{
			get
			{
				return this._Ix;
			}
			set
			{
				if ((this._Ix != value))
				{
					this._Ix = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wx", DbType="Float")]
		public System.Nullable<double> Wx
		{
			get
			{
				return this._Wx;
			}
			set
			{
				if ((this._Wx != value))
				{
					this._Wx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rx", DbType="Float")]
		public System.Nullable<double> rx
		{
			get
			{
				return this._rx;
			}
			set
			{
				if ((this._rx != value))
				{
					this._rx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zx", DbType="Float")]
		public System.Nullable<double> Zx
		{
			get
			{
				return this._Zx;
			}
			set
			{
				if ((this._Zx != value))
				{
					this._Zx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iy", DbType="Float")]
		public System.Nullable<double> Iy
		{
			get
			{
				return this._Iy;
			}
			set
			{
				if ((this._Iy != value))
				{
					this._Iy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wy", DbType="Float")]
		public System.Nullable<double> Wy
		{
			get
			{
				return this._Wy;
			}
			set
			{
				if ((this._Wy != value))
				{
					this._Wy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ry", DbType="Float")]
		public System.Nullable<double> ry
		{
			get
			{
				return this._ry;
			}
			set
			{
				if ((this._ry != value))
				{
					this._ry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zy", DbType="Float")]
		public System.Nullable<double> Zy
		{
			get
			{
				return this._Zy;
			}
			set
			{
				if ((this._Zy != value))
				{
					this._Zy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rT", DbType="Float")]
		public System.Nullable<double> rT
		{
			get
			{
				return this._rT;
			}
			set
			{
				if ((this._rT != value))
				{
					this._rT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IT", DbType="Float")]
		public System.Nullable<double> IT
		{
			get
			{
				return this._IT;
			}
			set
			{
				if ((this._IT != value))
				{
					this._IT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cw", DbType="Float")]
		public System.Nullable<double> Cw
		{
			get
			{
				return this._Cw;
			}
			set
			{
				if ((this._Cw != value))
				{
					this._Cw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfCode", DbType="Int")]
		public System.Nullable<int> ProfCode
		{
			get
			{
				return this._ProfCode;
			}
			set
			{
				if ((this._ProfCode != value))
				{
					this._ProfCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fabrication", DbType="Int")]
		public System.Nullable<int> Fabrication
		{
			get
			{
				return this._Fabrication;
			}
			set
			{
				if ((this._Fabrication != value))
				{
					this._Fabrication = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="Int")]
		public System.Nullable<int> R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this._R = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PSa")]
	public partial class PSa
	{
		
		private System.Nullable<int> _ID;
		
		private string _nome;
		
		private System.Nullable<double> _peso;
		
		private System.Nullable<double> _A;
		
		private System.Nullable<int> _d;
		
		private System.Nullable<double> _tw;
		
		private System.Nullable<int> _bfs;
		
		private System.Nullable<int> _bfi;
		
		private System.Nullable<double> _tfs;
		
		private System.Nullable<double> _tfi;
		
		private System.Nullable<double> _Ix;
		
		private System.Nullable<double> _Wxs;
		
		private System.Nullable<double> _Wxi;
		
		private System.Nullable<double> _rx;
		
		private System.Nullable<double> _Zx;
		
		private System.Nullable<double> _Iy;
		
		private System.Nullable<double> _Wy;
		
		private System.Nullable<double> _ry;
		
		private System.Nullable<double> _Zy;
		
		private System.Nullable<double> _rT;
		
		private System.Nullable<double> _IT;
		
		private System.Nullable<double> _Cw;
		
		private System.Nullable<int> _ProfCode;
		
		private System.Nullable<int> _Fabrication;
		
		private System.Nullable<int> _R;
		
		public PSa()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(50)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this._nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Float")]
		public System.Nullable<double> peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this._peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Float")]
		public System.Nullable<double> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this._A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d", DbType="Int")]
		public System.Nullable<int> d
		{
			get
			{
				return this._d;
			}
			set
			{
				if ((this._d != value))
				{
					this._d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tw", DbType="Float")]
		public System.Nullable<double> tw
		{
			get
			{
				return this._tw;
			}
			set
			{
				if ((this._tw != value))
				{
					this._tw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bfs", DbType="Int")]
		public System.Nullable<int> bfs
		{
			get
			{
				return this._bfs;
			}
			set
			{
				if ((this._bfs != value))
				{
					this._bfs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bfi", DbType="Int")]
		public System.Nullable<int> bfi
		{
			get
			{
				return this._bfi;
			}
			set
			{
				if ((this._bfi != value))
				{
					this._bfi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tfs", DbType="Float")]
		public System.Nullable<double> tfs
		{
			get
			{
				return this._tfs;
			}
			set
			{
				if ((this._tfs != value))
				{
					this._tfs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tfi", DbType="Float")]
		public System.Nullable<double> tfi
		{
			get
			{
				return this._tfi;
			}
			set
			{
				if ((this._tfi != value))
				{
					this._tfi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ix", DbType="Float")]
		public System.Nullable<double> Ix
		{
			get
			{
				return this._Ix;
			}
			set
			{
				if ((this._Ix != value))
				{
					this._Ix = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wxs", DbType="Float")]
		public System.Nullable<double> Wxs
		{
			get
			{
				return this._Wxs;
			}
			set
			{
				if ((this._Wxs != value))
				{
					this._Wxs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wxi", DbType="Float")]
		public System.Nullable<double> Wxi
		{
			get
			{
				return this._Wxi;
			}
			set
			{
				if ((this._Wxi != value))
				{
					this._Wxi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rx", DbType="Float")]
		public System.Nullable<double> rx
		{
			get
			{
				return this._rx;
			}
			set
			{
				if ((this._rx != value))
				{
					this._rx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zx", DbType="Float")]
		public System.Nullable<double> Zx
		{
			get
			{
				return this._Zx;
			}
			set
			{
				if ((this._Zx != value))
				{
					this._Zx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iy", DbType="Float")]
		public System.Nullable<double> Iy
		{
			get
			{
				return this._Iy;
			}
			set
			{
				if ((this._Iy != value))
				{
					this._Iy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wy", DbType="Float")]
		public System.Nullable<double> Wy
		{
			get
			{
				return this._Wy;
			}
			set
			{
				if ((this._Wy != value))
				{
					this._Wy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ry", DbType="Float")]
		public System.Nullable<double> ry
		{
			get
			{
				return this._ry;
			}
			set
			{
				if ((this._ry != value))
				{
					this._ry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zy", DbType="Float")]
		public System.Nullable<double> Zy
		{
			get
			{
				return this._Zy;
			}
			set
			{
				if ((this._Zy != value))
				{
					this._Zy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rT", DbType="Float")]
		public System.Nullable<double> rT
		{
			get
			{
				return this._rT;
			}
			set
			{
				if ((this._rT != value))
				{
					this._rT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IT", DbType="Float")]
		public System.Nullable<double> IT
		{
			get
			{
				return this._IT;
			}
			set
			{
				if ((this._IT != value))
				{
					this._IT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cw", DbType="Float")]
		public System.Nullable<double> Cw
		{
			get
			{
				return this._Cw;
			}
			set
			{
				if ((this._Cw != value))
				{
					this._Cw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfCode", DbType="Int")]
		public System.Nullable<int> ProfCode
		{
			get
			{
				return this._ProfCode;
			}
			set
			{
				if ((this._ProfCode != value))
				{
					this._ProfCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fabrication", DbType="Int")]
		public System.Nullable<int> Fabrication
		{
			get
			{
				return this._Fabrication;
			}
			set
			{
				if ((this._Fabrication != value))
				{
					this._Fabrication = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="Int")]
		public System.Nullable<int> R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this._R = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sqlite_sequence")]
	public partial class sqlite_sequence
	{
		
		private string _name;
		
		private string _seq;
		
		public sqlite_sequence()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(MAX)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seq", DbType="NVarChar(MAX)")]
		public string seq
		{
			get
			{
				return this._seq;
			}
			set
			{
				if ((this._seq != value))
				{
					this._seq = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T")]
	public partial class T
	{
		
		private System.Nullable<int> _ID;
		
		private string _nome;
		
		private System.Nullable<double> _peso;
		
		private System.Nullable<double> _A;
		
		private System.Nullable<int> _d;
		
		private System.Nullable<double> _tw;
		
		private System.Nullable<int> _bf;
		
		private System.Nullable<double> _tf;
		
		private System.Nullable<double> _Ix;
		
		private System.Nullable<double> _Wx;
		
		private System.Nullable<double> _rx;
		
		private System.Nullable<double> _Zx;
		
		private System.Nullable<double> _Iy;
		
		private System.Nullable<double> _Wy;
		
		private System.Nullable<double> _ry;
		
		private System.Nullable<double> _Zy;
		
		private System.Nullable<double> _rT;
		
		private System.Nullable<double> _IT;
		
		private System.Nullable<double> _Cw;
		
		private System.Nullable<int> _ProfCode;
		
		private System.Nullable<int> _Fabrication;
		
		public T()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(50)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this._nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Float")]
		public System.Nullable<double> peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this._peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Float")]
		public System.Nullable<double> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this._A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d", DbType="Int")]
		public System.Nullable<int> d
		{
			get
			{
				return this._d;
			}
			set
			{
				if ((this._d != value))
				{
					this._d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tw", DbType="Float")]
		public System.Nullable<double> tw
		{
			get
			{
				return this._tw;
			}
			set
			{
				if ((this._tw != value))
				{
					this._tw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bf", DbType="Int")]
		public System.Nullable<int> bf
		{
			get
			{
				return this._bf;
			}
			set
			{
				if ((this._bf != value))
				{
					this._bf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tf", DbType="Float")]
		public System.Nullable<double> tf
		{
			get
			{
				return this._tf;
			}
			set
			{
				if ((this._tf != value))
				{
					this._tf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ix", DbType="Float")]
		public System.Nullable<double> Ix
		{
			get
			{
				return this._Ix;
			}
			set
			{
				if ((this._Ix != value))
				{
					this._Ix = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wx", DbType="Float")]
		public System.Nullable<double> Wx
		{
			get
			{
				return this._Wx;
			}
			set
			{
				if ((this._Wx != value))
				{
					this._Wx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rx", DbType="Float")]
		public System.Nullable<double> rx
		{
			get
			{
				return this._rx;
			}
			set
			{
				if ((this._rx != value))
				{
					this._rx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zx", DbType="Float")]
		public System.Nullable<double> Zx
		{
			get
			{
				return this._Zx;
			}
			set
			{
				if ((this._Zx != value))
				{
					this._Zx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iy", DbType="Float")]
		public System.Nullable<double> Iy
		{
			get
			{
				return this._Iy;
			}
			set
			{
				if ((this._Iy != value))
				{
					this._Iy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wy", DbType="Float")]
		public System.Nullable<double> Wy
		{
			get
			{
				return this._Wy;
			}
			set
			{
				if ((this._Wy != value))
				{
					this._Wy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ry", DbType="Float")]
		public System.Nullable<double> ry
		{
			get
			{
				return this._ry;
			}
			set
			{
				if ((this._ry != value))
				{
					this._ry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zy", DbType="Float")]
		public System.Nullable<double> Zy
		{
			get
			{
				return this._Zy;
			}
			set
			{
				if ((this._Zy != value))
				{
					this._Zy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rT", DbType="Float")]
		public System.Nullable<double> rT
		{
			get
			{
				return this._rT;
			}
			set
			{
				if ((this._rT != value))
				{
					this._rT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IT", DbType="Float")]
		public System.Nullable<double> IT
		{
			get
			{
				return this._IT;
			}
			set
			{
				if ((this._IT != value))
				{
					this._IT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cw", DbType="Float")]
		public System.Nullable<double> Cw
		{
			get
			{
				return this._Cw;
			}
			set
			{
				if ((this._Cw != value))
				{
					this._Cw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfCode", DbType="Int")]
		public System.Nullable<int> ProfCode
		{
			get
			{
				return this._ProfCode;
			}
			set
			{
				if ((this._ProfCode != value))
				{
					this._ProfCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fabrication", DbType="Int")]
		public System.Nullable<int> Fabrication
		{
			get
			{
				return this._Fabrication;
			}
			set
			{
				if ((this._Fabrication != value))
				{
					this._Fabrication = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TQ")]
	public partial class TQ
	{
		
		private System.Nullable<int> _ID;
		
		private string _nome;
		
		private System.Nullable<double> _peso;
		
		private System.Nullable<double> _A;
		
		private System.Nullable<int> _d;
		
		private System.Nullable<double> _tw;
		
		private System.Nullable<int> _bf;
		
		private System.Nullable<double> _tf;
		
		private System.Nullable<double> _Ix;
		
		private System.Nullable<double> _Wx;
		
		private System.Nullable<double> _rx;
		
		private System.Nullable<double> _Zx;
		
		private System.Nullable<double> _Iy;
		
		private System.Nullable<double> _Wy;
		
		private System.Nullable<double> _ry;
		
		private System.Nullable<double> _Zy;
		
		private System.Nullable<double> _rT;
		
		private System.Nullable<double> _IT;
		
		private System.Nullable<double> _Cw;
		
		private System.Nullable<int> _ProfCode;
		
		private System.Nullable<int> _Fabrication;
		
		public TQ()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(50)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this._nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Float")]
		public System.Nullable<double> peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this._peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Float")]
		public System.Nullable<double> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this._A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d", DbType="Int")]
		public System.Nullable<int> d
		{
			get
			{
				return this._d;
			}
			set
			{
				if ((this._d != value))
				{
					this._d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tw", DbType="Float")]
		public System.Nullable<double> tw
		{
			get
			{
				return this._tw;
			}
			set
			{
				if ((this._tw != value))
				{
					this._tw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bf", DbType="Int")]
		public System.Nullable<int> bf
		{
			get
			{
				return this._bf;
			}
			set
			{
				if ((this._bf != value))
				{
					this._bf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tf", DbType="Float")]
		public System.Nullable<double> tf
		{
			get
			{
				return this._tf;
			}
			set
			{
				if ((this._tf != value))
				{
					this._tf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ix", DbType="Float")]
		public System.Nullable<double> Ix
		{
			get
			{
				return this._Ix;
			}
			set
			{
				if ((this._Ix != value))
				{
					this._Ix = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wx", DbType="Float")]
		public System.Nullable<double> Wx
		{
			get
			{
				return this._Wx;
			}
			set
			{
				if ((this._Wx != value))
				{
					this._Wx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rx", DbType="Float")]
		public System.Nullable<double> rx
		{
			get
			{
				return this._rx;
			}
			set
			{
				if ((this._rx != value))
				{
					this._rx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zx", DbType="Float")]
		public System.Nullable<double> Zx
		{
			get
			{
				return this._Zx;
			}
			set
			{
				if ((this._Zx != value))
				{
					this._Zx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iy", DbType="Float")]
		public System.Nullable<double> Iy
		{
			get
			{
				return this._Iy;
			}
			set
			{
				if ((this._Iy != value))
				{
					this._Iy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wy", DbType="Float")]
		public System.Nullable<double> Wy
		{
			get
			{
				return this._Wy;
			}
			set
			{
				if ((this._Wy != value))
				{
					this._Wy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ry", DbType="Float")]
		public System.Nullable<double> ry
		{
			get
			{
				return this._ry;
			}
			set
			{
				if ((this._ry != value))
				{
					this._ry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zy", DbType="Float")]
		public System.Nullable<double> Zy
		{
			get
			{
				return this._Zy;
			}
			set
			{
				if ((this._Zy != value))
				{
					this._Zy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rT", DbType="Float")]
		public System.Nullable<double> rT
		{
			get
			{
				return this._rT;
			}
			set
			{
				if ((this._rT != value))
				{
					this._rT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IT", DbType="Float")]
		public System.Nullable<double> IT
		{
			get
			{
				return this._IT;
			}
			set
			{
				if ((this._IT != value))
				{
					this._IT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cw", DbType="Float")]
		public System.Nullable<double> Cw
		{
			get
			{
				return this._Cw;
			}
			set
			{
				if ((this._Cw != value))
				{
					this._Cw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfCode", DbType="Int")]
		public System.Nullable<int> ProfCode
		{
			get
			{
				return this._ProfCode;
			}
			set
			{
				if ((this._ProfCode != value))
				{
					this._ProfCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fabrication", DbType="Int")]
		public System.Nullable<int> Fabrication
		{
			get
			{
				return this._Fabrication;
			}
			set
			{
				if ((this._Fabrication != value))
				{
					this._Fabrication = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TR")]
	public partial class TR
	{
		
		private System.Nullable<int> _ID;
		
		private string _nome;
		
		private System.Nullable<double> _peso;
		
		private System.Nullable<double> _A;
		
		private System.Nullable<int> _d;
		
		private System.Nullable<double> _tw;
		
		private System.Nullable<int> _bf;
		
		private System.Nullable<double> _tf;
		
		private System.Nullable<double> _Ix;
		
		private System.Nullable<double> _Wx;
		
		private System.Nullable<double> _rx;
		
		private System.Nullable<double> _Zx;
		
		private System.Nullable<double> _Iy;
		
		private System.Nullable<double> _Wy;
		
		private System.Nullable<double> _ry;
		
		private System.Nullable<double> _Zy;
		
		private System.Nullable<double> _rT;
		
		private System.Nullable<double> _IT;
		
		private System.Nullable<double> _Cw;
		
		private System.Nullable<int> _ProfCode;
		
		private System.Nullable<int> _Fabrication;
		
		public TR()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(50)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this._nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Float")]
		public System.Nullable<double> peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this._peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Float")]
		public System.Nullable<double> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this._A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d", DbType="Int")]
		public System.Nullable<int> d
		{
			get
			{
				return this._d;
			}
			set
			{
				if ((this._d != value))
				{
					this._d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tw", DbType="Float")]
		public System.Nullable<double> tw
		{
			get
			{
				return this._tw;
			}
			set
			{
				if ((this._tw != value))
				{
					this._tw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bf", DbType="Int")]
		public System.Nullable<int> bf
		{
			get
			{
				return this._bf;
			}
			set
			{
				if ((this._bf != value))
				{
					this._bf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tf", DbType="Float")]
		public System.Nullable<double> tf
		{
			get
			{
				return this._tf;
			}
			set
			{
				if ((this._tf != value))
				{
					this._tf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ix", DbType="Float")]
		public System.Nullable<double> Ix
		{
			get
			{
				return this._Ix;
			}
			set
			{
				if ((this._Ix != value))
				{
					this._Ix = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wx", DbType="Float")]
		public System.Nullable<double> Wx
		{
			get
			{
				return this._Wx;
			}
			set
			{
				if ((this._Wx != value))
				{
					this._Wx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rx", DbType="Float")]
		public System.Nullable<double> rx
		{
			get
			{
				return this._rx;
			}
			set
			{
				if ((this._rx != value))
				{
					this._rx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zx", DbType="Float")]
		public System.Nullable<double> Zx
		{
			get
			{
				return this._Zx;
			}
			set
			{
				if ((this._Zx != value))
				{
					this._Zx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iy", DbType="Float")]
		public System.Nullable<double> Iy
		{
			get
			{
				return this._Iy;
			}
			set
			{
				if ((this._Iy != value))
				{
					this._Iy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wy", DbType="Float")]
		public System.Nullable<double> Wy
		{
			get
			{
				return this._Wy;
			}
			set
			{
				if ((this._Wy != value))
				{
					this._Wy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ry", DbType="Float")]
		public System.Nullable<double> ry
		{
			get
			{
				return this._ry;
			}
			set
			{
				if ((this._ry != value))
				{
					this._ry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zy", DbType="Float")]
		public System.Nullable<double> Zy
		{
			get
			{
				return this._Zy;
			}
			set
			{
				if ((this._Zy != value))
				{
					this._Zy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rT", DbType="Float")]
		public System.Nullable<double> rT
		{
			get
			{
				return this._rT;
			}
			set
			{
				if ((this._rT != value))
				{
					this._rT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IT", DbType="Float")]
		public System.Nullable<double> IT
		{
			get
			{
				return this._IT;
			}
			set
			{
				if ((this._IT != value))
				{
					this._IT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cw", DbType="Float")]
		public System.Nullable<double> Cw
		{
			get
			{
				return this._Cw;
			}
			set
			{
				if ((this._Cw != value))
				{
					this._Cw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfCode", DbType="Int")]
		public System.Nullable<int> ProfCode
		{
			get
			{
				return this._ProfCode;
			}
			set
			{
				if ((this._ProfCode != value))
				{
					this._ProfCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fabrication", DbType="Int")]
		public System.Nullable<int> Fabrication
		{
			get
			{
				return this._Fabrication;
			}
			set
			{
				if ((this._Fabrication != value))
				{
					this._Fabrication = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TW")]
	public partial class TW
	{
		
		private System.Nullable<int> _ID;
		
		private string _nome;
		
		private System.Nullable<double> _peso;
		
		private System.Nullable<double> _A;
		
		private System.Nullable<int> _d;
		
		private System.Nullable<double> _tw1;
		
		private System.Nullable<int> _bf;
		
		private System.Nullable<double> _tf;
		
		private System.Nullable<double> _Ix;
		
		private System.Nullable<double> _Wx;
		
		private System.Nullable<double> _rx;
		
		private System.Nullable<double> _Zx;
		
		private System.Nullable<double> _Iy;
		
		private System.Nullable<double> _Wy;
		
		private System.Nullable<double> _ry;
		
		private System.Nullable<double> _Zy;
		
		private System.Nullable<double> _rT;
		
		private System.Nullable<double> _IT;
		
		private System.Nullable<double> _Cw;
		
		private System.Nullable<int> _ProfCode;
		
		private System.Nullable<int> _Fabrication;
		
		public TW()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(50)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this._nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Float")]
		public System.Nullable<double> peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this._peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Float")]
		public System.Nullable<double> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this._A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d", DbType="Int")]
		public System.Nullable<int> d
		{
			get
			{
				return this._d;
			}
			set
			{
				if ((this._d != value))
				{
					this._d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="tw", Storage="_tw1", DbType="Float")]
		public System.Nullable<double> tw1
		{
			get
			{
				return this._tw1;
			}
			set
			{
				if ((this._tw1 != value))
				{
					this._tw1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bf", DbType="Int")]
		public System.Nullable<int> bf
		{
			get
			{
				return this._bf;
			}
			set
			{
				if ((this._bf != value))
				{
					this._bf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tf", DbType="Float")]
		public System.Nullable<double> tf
		{
			get
			{
				return this._tf;
			}
			set
			{
				if ((this._tf != value))
				{
					this._tf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ix", DbType="Float")]
		public System.Nullable<double> Ix
		{
			get
			{
				return this._Ix;
			}
			set
			{
				if ((this._Ix != value))
				{
					this._Ix = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wx", DbType="Float")]
		public System.Nullable<double> Wx
		{
			get
			{
				return this._Wx;
			}
			set
			{
				if ((this._Wx != value))
				{
					this._Wx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rx", DbType="Float")]
		public System.Nullable<double> rx
		{
			get
			{
				return this._rx;
			}
			set
			{
				if ((this._rx != value))
				{
					this._rx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zx", DbType="Float")]
		public System.Nullable<double> Zx
		{
			get
			{
				return this._Zx;
			}
			set
			{
				if ((this._Zx != value))
				{
					this._Zx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iy", DbType="Float")]
		public System.Nullable<double> Iy
		{
			get
			{
				return this._Iy;
			}
			set
			{
				if ((this._Iy != value))
				{
					this._Iy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wy", DbType="Float")]
		public System.Nullable<double> Wy
		{
			get
			{
				return this._Wy;
			}
			set
			{
				if ((this._Wy != value))
				{
					this._Wy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ry", DbType="Float")]
		public System.Nullable<double> ry
		{
			get
			{
				return this._ry;
			}
			set
			{
				if ((this._ry != value))
				{
					this._ry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zy", DbType="Float")]
		public System.Nullable<double> Zy
		{
			get
			{
				return this._Zy;
			}
			set
			{
				if ((this._Zy != value))
				{
					this._Zy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rT", DbType="Float")]
		public System.Nullable<double> rT
		{
			get
			{
				return this._rT;
			}
			set
			{
				if ((this._rT != value))
				{
					this._rT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IT", DbType="Float")]
		public System.Nullable<double> IT
		{
			get
			{
				return this._IT;
			}
			set
			{
				if ((this._IT != value))
				{
					this._IT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cw", DbType="Float")]
		public System.Nullable<double> Cw
		{
			get
			{
				return this._Cw;
			}
			set
			{
				if ((this._Cw != value))
				{
					this._Cw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfCode", DbType="Int")]
		public System.Nullable<int> ProfCode
		{
			get
			{
				return this._ProfCode;
			}
			set
			{
				if ((this._ProfCode != value))
				{
					this._ProfCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fabrication", DbType="Int")]
		public System.Nullable<int> Fabrication
		{
			get
			{
				return this._Fabrication;
			}
			set
			{
				if ((this._Fabrication != value))
				{
					this._Fabrication = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VS")]
	public partial class VS
	{
		
		private System.Nullable<int> _ID;
		
		private string _nome;
		
		private System.Nullable<double> _peso;
		
		private System.Nullable<double> _A;
		
		private System.Nullable<int> _d;
		
		private System.Nullable<double> _tw;
		
		private System.Nullable<int> _bf;
		
		private System.Nullable<double> _tf;
		
		private System.Nullable<double> _Ix;
		
		private System.Nullable<double> _Wx;
		
		private System.Nullable<double> _rx;
		
		private System.Nullable<double> _Zx;
		
		private System.Nullable<double> _Iy;
		
		private System.Nullable<double> _Wy;
		
		private System.Nullable<double> _ry;
		
		private System.Nullable<double> _Zy;
		
		private System.Nullable<double> _rT;
		
		private System.Nullable<double> _IT;
		
		private System.Nullable<double> _Cw;
		
		private System.Nullable<int> _ProfCode;
		
		private System.Nullable<int> _Fabrication;
		
		private System.Nullable<int> _R;
		
		public VS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(50)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this._nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Float")]
		public System.Nullable<double> peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this._peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Float")]
		public System.Nullable<double> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this._A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d", DbType="Int")]
		public System.Nullable<int> d
		{
			get
			{
				return this._d;
			}
			set
			{
				if ((this._d != value))
				{
					this._d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tw", DbType="Float")]
		public System.Nullable<double> tw
		{
			get
			{
				return this._tw;
			}
			set
			{
				if ((this._tw != value))
				{
					this._tw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bf", DbType="Int")]
		public System.Nullable<int> bf
		{
			get
			{
				return this._bf;
			}
			set
			{
				if ((this._bf != value))
				{
					this._bf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tf", DbType="Float")]
		public System.Nullable<double> tf
		{
			get
			{
				return this._tf;
			}
			set
			{
				if ((this._tf != value))
				{
					this._tf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ix", DbType="Float")]
		public System.Nullable<double> Ix
		{
			get
			{
				return this._Ix;
			}
			set
			{
				if ((this._Ix != value))
				{
					this._Ix = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wx", DbType="Float")]
		public System.Nullable<double> Wx
		{
			get
			{
				return this._Wx;
			}
			set
			{
				if ((this._Wx != value))
				{
					this._Wx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rx", DbType="Float")]
		public System.Nullable<double> rx
		{
			get
			{
				return this._rx;
			}
			set
			{
				if ((this._rx != value))
				{
					this._rx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zx", DbType="Float")]
		public System.Nullable<double> Zx
		{
			get
			{
				return this._Zx;
			}
			set
			{
				if ((this._Zx != value))
				{
					this._Zx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iy", DbType="Float")]
		public System.Nullable<double> Iy
		{
			get
			{
				return this._Iy;
			}
			set
			{
				if ((this._Iy != value))
				{
					this._Iy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wy", DbType="Float")]
		public System.Nullable<double> Wy
		{
			get
			{
				return this._Wy;
			}
			set
			{
				if ((this._Wy != value))
				{
					this._Wy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ry", DbType="Float")]
		public System.Nullable<double> ry
		{
			get
			{
				return this._ry;
			}
			set
			{
				if ((this._ry != value))
				{
					this._ry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zy", DbType="Float")]
		public System.Nullable<double> Zy
		{
			get
			{
				return this._Zy;
			}
			set
			{
				if ((this._Zy != value))
				{
					this._Zy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rT", DbType="Float")]
		public System.Nullable<double> rT
		{
			get
			{
				return this._rT;
			}
			set
			{
				if ((this._rT != value))
				{
					this._rT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IT", DbType="Float")]
		public System.Nullable<double> IT
		{
			get
			{
				return this._IT;
			}
			set
			{
				if ((this._IT != value))
				{
					this._IT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cw", DbType="Float")]
		public System.Nullable<double> Cw
		{
			get
			{
				return this._Cw;
			}
			set
			{
				if ((this._Cw != value))
				{
					this._Cw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfCode", DbType="Int")]
		public System.Nullable<int> ProfCode
		{
			get
			{
				return this._ProfCode;
			}
			set
			{
				if ((this._ProfCode != value))
				{
					this._ProfCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fabrication", DbType="Int")]
		public System.Nullable<int> Fabrication
		{
			get
			{
				return this._Fabrication;
			}
			set
			{
				if ((this._Fabrication != value))
				{
					this._Fabrication = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="Int")]
		public System.Nullable<int> R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this._R = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VSM")]
	public partial class VSM
	{
		
		private System.Nullable<int> _ID;
		
		private string _nome;
		
		private System.Nullable<double> _peso;
		
		private System.Nullable<double> _A;
		
		private System.Nullable<int> _d;
		
		private System.Nullable<double> _tw;
		
		private System.Nullable<int> _bfs;
		
		private System.Nullable<int> _bfi;
		
		private System.Nullable<double> _tfs;
		
		private System.Nullable<double> _tfi;
		
		private System.Nullable<double> _Ix;
		
		private System.Nullable<double> _Wxs;
		
		private System.Nullable<double> _Wxi;
		
		private System.Nullable<double> _rx;
		
		private System.Nullable<double> _Zx;
		
		private System.Nullable<double> _Iy;
		
		private System.Nullable<double> _Wy;
		
		private System.Nullable<double> _ry;
		
		private System.Nullable<double> _Zy;
		
		private System.Nullable<double> _rT;
		
		private System.Nullable<double> _IT;
		
		private System.Nullable<double> _Cw;
		
		private System.Nullable<int> _ProfCode;
		
		private System.Nullable<int> _Fabrication;
		
		private System.Nullable<int> _R;
		
		public VSM()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(50)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this._nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Float")]
		public System.Nullable<double> peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this._peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Float")]
		public System.Nullable<double> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this._A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d", DbType="Int")]
		public System.Nullable<int> d
		{
			get
			{
				return this._d;
			}
			set
			{
				if ((this._d != value))
				{
					this._d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tw", DbType="Float")]
		public System.Nullable<double> tw
		{
			get
			{
				return this._tw;
			}
			set
			{
				if ((this._tw != value))
				{
					this._tw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bfs", DbType="Int")]
		public System.Nullable<int> bfs
		{
			get
			{
				return this._bfs;
			}
			set
			{
				if ((this._bfs != value))
				{
					this._bfs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bfi", DbType="Int")]
		public System.Nullable<int> bfi
		{
			get
			{
				return this._bfi;
			}
			set
			{
				if ((this._bfi != value))
				{
					this._bfi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tfs", DbType="Float")]
		public System.Nullable<double> tfs
		{
			get
			{
				return this._tfs;
			}
			set
			{
				if ((this._tfs != value))
				{
					this._tfs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tfi", DbType="Float")]
		public System.Nullable<double> tfi
		{
			get
			{
				return this._tfi;
			}
			set
			{
				if ((this._tfi != value))
				{
					this._tfi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ix", DbType="Float")]
		public System.Nullable<double> Ix
		{
			get
			{
				return this._Ix;
			}
			set
			{
				if ((this._Ix != value))
				{
					this._Ix = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wxs", DbType="Float")]
		public System.Nullable<double> Wxs
		{
			get
			{
				return this._Wxs;
			}
			set
			{
				if ((this._Wxs != value))
				{
					this._Wxs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wxi", DbType="Float")]
		public System.Nullable<double> Wxi
		{
			get
			{
				return this._Wxi;
			}
			set
			{
				if ((this._Wxi != value))
				{
					this._Wxi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rx", DbType="Float")]
		public System.Nullable<double> rx
		{
			get
			{
				return this._rx;
			}
			set
			{
				if ((this._rx != value))
				{
					this._rx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zx", DbType="Float")]
		public System.Nullable<double> Zx
		{
			get
			{
				return this._Zx;
			}
			set
			{
				if ((this._Zx != value))
				{
					this._Zx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iy", DbType="Float")]
		public System.Nullable<double> Iy
		{
			get
			{
				return this._Iy;
			}
			set
			{
				if ((this._Iy != value))
				{
					this._Iy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wy", DbType="Float")]
		public System.Nullable<double> Wy
		{
			get
			{
				return this._Wy;
			}
			set
			{
				if ((this._Wy != value))
				{
					this._Wy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ry", DbType="Float")]
		public System.Nullable<double> ry
		{
			get
			{
				return this._ry;
			}
			set
			{
				if ((this._ry != value))
				{
					this._ry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zy", DbType="Float")]
		public System.Nullable<double> Zy
		{
			get
			{
				return this._Zy;
			}
			set
			{
				if ((this._Zy != value))
				{
					this._Zy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rT", DbType="Float")]
		public System.Nullable<double> rT
		{
			get
			{
				return this._rT;
			}
			set
			{
				if ((this._rT != value))
				{
					this._rT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IT", DbType="Float")]
		public System.Nullable<double> IT
		{
			get
			{
				return this._IT;
			}
			set
			{
				if ((this._IT != value))
				{
					this._IT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cw", DbType="Float")]
		public System.Nullable<double> Cw
		{
			get
			{
				return this._Cw;
			}
			set
			{
				if ((this._Cw != value))
				{
					this._Cw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfCode", DbType="Int")]
		public System.Nullable<int> ProfCode
		{
			get
			{
				return this._ProfCode;
			}
			set
			{
				if ((this._ProfCode != value))
				{
					this._ProfCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fabrication", DbType="Int")]
		public System.Nullable<int> Fabrication
		{
			get
			{
				return this._Fabrication;
			}
			set
			{
				if ((this._Fabrication != value))
				{
					this._Fabrication = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="Int")]
		public System.Nullable<int> R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this._R = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Material")]
	public partial class Material : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _name;
		
		private double _E;
		
		private double _G;
		
		private double _Fy;
		
		private double _Fu;
		
		private double _unitWeight;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnEChanging(double value);
    partial void OnEChanged();
    partial void OnGChanging(double value);
    partial void OnGChanged();
    partial void OnFyChanging(double value);
    partial void OnFyChanged();
    partial void OnFuChanging(double value);
    partial void OnFuChanged();
    partial void OnunitWeightChanging(double value);
    partial void OnunitWeightChanged();
    #endregion
		
		public Material()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E", DbType="Float NOT NULL")]
		public double E
		{
			get
			{
				return this._E;
			}
			set
			{
				if ((this._E != value))
				{
					this.OnEChanging(value);
					this.SendPropertyChanging();
					this._E = value;
					this.SendPropertyChanged("E");
					this.OnEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G", DbType="Float NOT NULL")]
		public double G
		{
			get
			{
				return this._G;
			}
			set
			{
				if ((this._G != value))
				{
					this.OnGChanging(value);
					this.SendPropertyChanging();
					this._G = value;
					this.SendPropertyChanged("G");
					this.OnGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fy", DbType="Float NOT NULL")]
		public double Fy
		{
			get
			{
				return this._Fy;
			}
			set
			{
				if ((this._Fy != value))
				{
					this.OnFyChanging(value);
					this.SendPropertyChanging();
					this._Fy = value;
					this.SendPropertyChanged("Fy");
					this.OnFyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fu", DbType="Float NOT NULL")]
		public double Fu
		{
			get
			{
				return this._Fu;
			}
			set
			{
				if ((this._Fu != value))
				{
					this.OnFuChanging(value);
					this.SendPropertyChanging();
					this._Fu = value;
					this.SendPropertyChanged("Fu");
					this.OnFuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unitWeight", DbType="Float NOT NULL")]
		public double unitWeight
		{
			get
			{
				return this._unitWeight;
			}
			set
			{
				if ((this._unitWeight != value))
				{
					this.OnunitWeightChanging(value);
					this.SendPropertyChanging();
					this._unitWeight = value;
					this.SendPropertyChanged("unitWeight");
					this.OnunitWeightChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CVS")]
	public partial class CVS
	{
		
		private System.Nullable<int> _ID;
		
		private string _nome;
		
		private System.Nullable<double> _peso;
		
		private System.Nullable<double> _A;
		
		private System.Nullable<int> _d;
		
		private System.Nullable<double> _tw;
		
		private System.Nullable<int> _bf;
		
		private System.Nullable<double> _tf;
		
		private System.Nullable<double> _Ix;
		
		private System.Nullable<double> _Wx;
		
		private System.Nullable<double> _rx;
		
		private System.Nullable<double> _Zx;
		
		private System.Nullable<double> _Iy;
		
		private System.Nullable<double> _Wy;
		
		private System.Nullable<double> _ry;
		
		private System.Nullable<double> _Zy;
		
		private System.Nullable<double> _rT;
		
		private System.Nullable<double> _IT;
		
		private System.Nullable<double> _Cw;
		
		private System.Nullable<int> _ProfCode;
		
		private System.Nullable<int> _Fabrication;
		
		private System.Nullable<int> _R;
		
		public CVS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="NVarChar(50)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this._nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peso", DbType="Float")]
		public System.Nullable<double> peso
		{
			get
			{
				return this._peso;
			}
			set
			{
				if ((this._peso != value))
				{
					this._peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Float")]
		public System.Nullable<double> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this._A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d", DbType="Int")]
		public System.Nullable<int> d
		{
			get
			{
				return this._d;
			}
			set
			{
				if ((this._d != value))
				{
					this._d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tw", DbType="Float")]
		public System.Nullable<double> tw
		{
			get
			{
				return this._tw;
			}
			set
			{
				if ((this._tw != value))
				{
					this._tw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bf", DbType="Int")]
		public System.Nullable<int> bf
		{
			get
			{
				return this._bf;
			}
			set
			{
				if ((this._bf != value))
				{
					this._bf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tf", DbType="Float")]
		public System.Nullable<double> tf
		{
			get
			{
				return this._tf;
			}
			set
			{
				if ((this._tf != value))
				{
					this._tf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ix", DbType="Float")]
		public System.Nullable<double> Ix
		{
			get
			{
				return this._Ix;
			}
			set
			{
				if ((this._Ix != value))
				{
					this._Ix = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wx", DbType="Float")]
		public System.Nullable<double> Wx
		{
			get
			{
				return this._Wx;
			}
			set
			{
				if ((this._Wx != value))
				{
					this._Wx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rx", DbType="Float")]
		public System.Nullable<double> rx
		{
			get
			{
				return this._rx;
			}
			set
			{
				if ((this._rx != value))
				{
					this._rx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zx", DbType="Float")]
		public System.Nullable<double> Zx
		{
			get
			{
				return this._Zx;
			}
			set
			{
				if ((this._Zx != value))
				{
					this._Zx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iy", DbType="Float")]
		public System.Nullable<double> Iy
		{
			get
			{
				return this._Iy;
			}
			set
			{
				if ((this._Iy != value))
				{
					this._Iy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wy", DbType="Float")]
		public System.Nullable<double> Wy
		{
			get
			{
				return this._Wy;
			}
			set
			{
				if ((this._Wy != value))
				{
					this._Wy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ry", DbType="Float")]
		public System.Nullable<double> ry
		{
			get
			{
				return this._ry;
			}
			set
			{
				if ((this._ry != value))
				{
					this._ry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zy", DbType="Float")]
		public System.Nullable<double> Zy
		{
			get
			{
				return this._Zy;
			}
			set
			{
				if ((this._Zy != value))
				{
					this._Zy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rT", DbType="Float")]
		public System.Nullable<double> rT
		{
			get
			{
				return this._rT;
			}
			set
			{
				if ((this._rT != value))
				{
					this._rT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IT", DbType="Float")]
		public System.Nullable<double> IT
		{
			get
			{
				return this._IT;
			}
			set
			{
				if ((this._IT != value))
				{
					this._IT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cw", DbType="Float")]
		public System.Nullable<double> Cw
		{
			get
			{
				return this._Cw;
			}
			set
			{
				if ((this._Cw != value))
				{
					this._Cw = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfCode", DbType="Int")]
		public System.Nullable<int> ProfCode
		{
			get
			{
				return this._ProfCode;
			}
			set
			{
				if ((this._ProfCode != value))
				{
					this._ProfCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fabrication", DbType="Int")]
		public System.Nullable<int> Fabrication
		{
			get
			{
				return this._Fabrication;
			}
			set
			{
				if ((this._Fabrication != value))
				{
					this._Fabrication = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="Int")]
		public System.Nullable<int> R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this._R = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
